# Generated by Django 4.0.4 on 2022-09-05 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rateplan_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobokassaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
                ('payed_time', models.DateTimeField(default=None, null=True, verbose_name='Время оплаты')),
                ('canceled_time', models.DateTimeField(default=None, null=True, verbose_name='Время отмены')),
                ('hash', models.CharField(max_length=128, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rateplan', verbose_name='План')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
