# Generated by Django 4.0.4 on 2022-09-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_robokassatransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=20, unique=True, verbose_name='Промо код')),
                ('discount', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Скидка')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='Начало действия')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Конец действия')),
            ],
            options={
                'verbose_name': 'Промо код',
                'verbose_name_plural': 'Промо коды',
            },
        ),
    ]
