# Generated by Django 4.0.6 on 2022-12-21 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contract_team_member_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
