# Generated by Django 4.0.6 on 2022-12-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0004_alter_contract_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время записи лога')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.contract')),
            ],
        ),
    ]
