# Generated by Django 4.1.3 on 2022-12-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_contract_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlog',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contract'),
        ),
    ]
