# Generated by Django 4.1.3 on 2022-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_contractlog_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='full_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
