# Generated by Django 4.0.6 on 2023-01-25 11:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_rename_avatar_url_usermodel__avatar_url'),
        ('crm', '0010_alter_contractfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companymodel')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
            },
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='position',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BoardPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role',
                 models.CharField(choices=[('ADMIN', 'ADMIN'), ('OWN', 'Owner'), ('EMPL', 'Employee')], max_length=25)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.board'),
        ),
        migrations.AddField(
            model_name='contractstatus',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.board'),
        ),
    ]
