# Generated by Django 4.0.6 on 2023-01-26 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0011_board_contractstatus_color_contractstatus_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='team_member',
            new_name='board_member',
        ),
        migrations.RemoveField(
            model_name='board',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
    ]
