# Generated by Django 4.0.6 on 2023-01-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_rename_team_member_contract_board_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractstatus',
            options={'ordering': ['position'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
