# Generated by Django 4.0.6 on 2023-01-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0012_rename_team_member_contract_board_member_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractstatus',
            options={'ordering': ['position'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='color',
            field=models.CharField(
                choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'),
                         ('warning', 'Yellow'), ('info', 'Сyan'), ('white', 'White')], default='white', max_length=20),
        ),
    ]
