# Generated by Django 4.0.6 on 2023-01-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_contractstatus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='board',
        ),
        migrations.AlterField(
            model_name='contractstatus',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Сyan'), ('white', 'White')], default='white', max_length=20),
        ),
    ]
