# Generated by Django 4.0.6 on 2023-01-30 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0014_remove_contract_board_alter_contractstatus_color'),
        ('crm', '0015_alter_boardpermissions_role'),
    ]

    operations = [
    ]
