# Generated by Django 4.0.6 on 2023-01-30 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0016_merge_20230131_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONTRACT_CREATED', 'Создан договор'),
                                                     ('CONTRACT_STATUS_CHANGED', 'Изменен статус договора'),
                                                     ('CONTRACT_DELETED', 'Удален договор'),
                                                     ('STATUS_ADDED', 'Добавлен статус'),
                                                     ('STATUS_DELETED', 'Удален статус')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог доски',
                'verbose_name_plural': 'Логи доски',
            },
        ),
    ]
