# Generated by Django 4.0.6 on 2023-01-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0018_alter_boardlog_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpermissions',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
