# Generated by Django 4.0.6 on 2023-02-02 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_remove_boardpermissions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='last_status_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
