# Generated by Django 4.0.4 on 2022-08-23 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='template_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.templateslist'),
        ),
        migrations.AddField(
            model_name='sendingmailslist',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.newslettertemplate'),
        ),
        migrations.AddField(
            model_name='sendingmailslist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendingmails',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.contact', verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='sendingmails',
            name='sendingmails_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.sendingmailslist'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newslettertemplateslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newslettertemplate',
            name='newsletter_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.newslettertemplateslist', verbose_name='Newsletter List'),
        ),
        migrations.AddField(
            model_name='listcontainer',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.contact'),
        ),
        migrations.AddField(
            model_name='listcontainer',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.list'),
        ),
        migrations.AddField(
            model_name='list',
            name='list_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='findemails',
            name='request_for_search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.requestsforsearch'),
        ),
        migrations.AddField(
            model_name='contactcompany',
            name='company_branch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.companybranch'),
        ),
        migrations.AddField(
            model_name='contactcompany',
            name='company_size',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.companysizes'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.contactcompany'),
        ),
    ]
