# Generated by Django 4.0.4 on 2022-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcompany',
            name='apollo_hash',
            field=models.TextField(default=None, null=True, verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='location',
            field=models.TextField(default=None, null=True, verbose_name='Локация'),
        ),
    ]
