# Generated by Django 4.0.4 on 2022-08-27 11:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_contactcompany_apollo_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linkedin_link',
            field=models.TextField(null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position_in_company',
            field=models.CharField(max_length=128, null=True, verbose_name='Позиция в компании'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия'),
        ),
    ]
