# Generated by Django 4.0.4 on 2022-09-07 12:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0004_contact_linkedin_link_alter_contact_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт (наш, т.е внутренний, не созданный пользователем)',
                     'verbose_name_plural': 'Контакт (наши, т.е внутренние)'},
        ),
        migrations.CreateModel(
            name='UsersContacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=128, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None,
                                                                         verbose_name='Номер телефона')),
                ('position_in_company', models.CharField(max_length=128, null=True, verbose_name='Позиция в компании')),
                ('linkedin_link', models.TextField(null=True, verbose_name='LinkedIn')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='company.contactcompany')),
            ],
            options={
                'verbose_name': 'Контакт созданный пользователем',
                'verbose_name_plural': 'Контакты созданные пользователями',
            },
        ),
        migrations.AlterField(
            model_name='listcontainer',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.userscontacts'),
        ),
    ]
