# Generated by Django 4.0.4 on 2022-09-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0006_alter_sendingmails_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsforsearch',
            name='company_domain',
            field=models.CharField(max_length=30, null=True, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='requestsforsearch',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя (Кириллица)'),
        ),
        migrations.AlterField(
            model_name='requestsforsearch',
            name='name_lat',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя (Латиница)'),
        ),
        migrations.AlterField(
            model_name='requestsforsearch',
            name='surname',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия (Кириллица)'),
        ),
        migrations.AlterField(
            model_name='requestsforsearch',
            name='surname_lat',
            field=models.CharField(max_length=128, null=True, verbose_name='Фамилия (Латиница)'),
        ),
    ]
