# Generated by Django 4.0.4 on 2022-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0007_alter_requestsforsearch_company_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingmails',
            name='link',
            field=models.CharField(max_length=2000, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='sendingmails',
            name='theme',
            field=models.CharField(max_length=2000, verbose_name='Theme'),
        ),
    ]
