# Generated by Django 4.0.6 on 2023-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_sendingmails_link_alter_sendingmails_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='text_en',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='text_ru',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('DELETED', 'Deleted')], default='UNREAD', max_length=20),
        ),
    ]
