# Generated by Django 4.0.6 on 2023-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_notification_options_notification_redirect_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userscontacts',
            name='telegram_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
