# Generated by Django 4.0.6 on 2023-02-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_contact_telegram_id_userscontacts_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendingmails',
            options={'verbose_name': 'Письмо для отправки (Email)', 'verbose_name_plural': 'Письма для отправки (Email)'},
        ),
        migrations.CreateModel(
            name='SendingTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('theme', models.CharField(max_length=2000, verbose_name='Theme')),
                ('status', models.CharField(choices=[(1, 'Pending'), (2, 'Delivered'), (3, 'Error'), (4, 'Opened'), (5, 'Cancelled')], max_length=128, verbose_name='Status')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(verbose_name='Active')),
                ('template_name', models.TextField(null=True)),
                ('error_description', models.TextField(null=True, verbose_name='error_description')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.userscontacts', verbose_name='Recipient')),
                ('sendingmails_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.sendingmailslist')),
            ],
            options={
                'verbose_name': 'Письмо для отправки (Telegram)',
                'verbose_name_plural': 'Письма для отправки (Telegram)',
            },
        ),
    ]
