# Generated by Django 4.1.7 on 2023-03-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_contact_options_alter_contactcompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userscontacts',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя'),
        ),
    ]
